### PR TITLE
added a feature in utils.py

### PR DESCRIPTION
**Pull request by rashidkalwar**
just added a function that will fetch the title of a webpage using a webdriver.

### CODE REVIEW

**Comment by chavarera** [comment]
@rashidkalwar the function should accept driver and get title only.

Create utils function and import into driver.py and implement it

**Comment by rashidkalwar** [comment]
@chavarera, I will put the code in any file you want just let me know if the function is ok? if not what parameters do you want me to add? how it should operate?

**Comment by chavarera** [comment]
@rashidkalwar check example of getting user agent function implemented in driver.py

**Comment by rashidkalwar** [comment]
can you code me an example snippet so I can have a better idea?

**Comment by chavarera** [comment]
closing PR no update from long time

**Pull request closed without merging**
